plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-haml
AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/**'

Layout/LineLength:
  Exclude:
    - 'app/views/devise/shared/**'
