default: &default
  adapter: postgresql
  encoding: unicode

  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tolsky_chat_development
  password: <%= ENV["TOLSKY_CHAT_DATABASE_PASSWORD"] %>
  user: karina

test:
  <<: *default
  database: tolsky_chat_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

